[package]
name = "bls-signature-aggregation"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
ark-bls12-381 = "0.5.0"
ark-std = "0.5.0"
ark-serialize = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
